[zsh]
files = {
    "zsh/.zshrc"        = "~/.zshrc",
    "zsh/.zprofile"     = "~/.zprofile",
    "zsh/aliases.zsh"   = "~/aliases.zsh",
    "zsh/functions.zsh" = "~/functions.zsh",
    "zsh/fzf.zsh"       = "~/fzf.zsh",
    ".bashrc"           = "~/.bashrc"
}

[git]
files = {
    "git/.gitconfig"        = "~/.gitconfig",
    "git/.gitignore_global" = "~/.gitignore_global"
}

[zed]
files = {
    "zed/settings.json" = "~/.config/zed/settings.json",
    "zed/asevka.toml"   = "~/.config/zed/asevka.toml"
}

[app.config]
files = {
    ".config/Caddyfile"      = "~/.config/caddy/Caddyfile",
    ".config/bottom.toml"    = "~/.config/bottom/bottom.toml",
    ".config/config.ghostty" = "~/.config/ghostty/config",
    ".config/starship.toml"  = "~/.config/starship.toml"
}

[scripts]
files = { "bin/" = "~/bin/" }

[did]
files = { "did/" = "~/did/" }

[templates]
files = { "templates/" = "~/.config/templates/" }

[system]
files = { "Brewfile" = "~/Brewfile" }
